# Generated by Django 5.1.3 on 2025-01-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='center_id',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='voters',
            name='center_id',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='voters',
            name='id',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
    ]
