# Generated by Django 5.1.4 on 2025-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='location',
        ),
        migrations.RemoveField(
            model_name='center',
            name='name',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='name',
        ),
        migrations.AddField(
            model_name='center',
            name='vote',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='has_vote',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='center',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
