# Generated by Django 5.1.3 on 2025-01-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_center_center_id_alter_voters_center_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='choice',
            field=models.CharField(max_length=200),
        ),
    ]
